### ISSUE TITLE
Input in Docs sidebar links to Field

### ISSUE THREAD

**Issue by nathanforce** [diegohaz/reas#20]
Field renders and input with `id="input"` which leaves two html elements with the same `id` on the page.  The anchor chooses the first one, so it scrolls to Field.

**Comment by nathanforce** [comment]
I browsed quickly but didn't see where props like id are passed to the examples rendered in the docs page.

**Comment by diegohaz** [comment]
Good catch, @nathanforce. Thank you.

Since that's a very easy change, I'll mark it as `good first issue`. Would you like to work on this?

Instructions:

1. fork the repo;
2. change `id` prop on the first example: https://github.com/diegohaz/reas/blob/master/src/components/Field/Field.md;
3. `yarn install && yarn docs:build`;
4. open a Pull Request.

**Comment by nathanforce** [comment]
@diegohaz sure!
